CREATE DATABASE BANCOINVESTIMENTO
GO
USE BANCOINVESTIMENTO
GO
CREATE TABLE CULTURA(
	ID INT IDENTITY PRIMARY KEY,
	LOCAL_ARMAZENAMENTO VARCHAR(100) NOT NULL
)
CREATE TABLE ASSOCIADO(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	DATA_HORA DATETIME NOT NULL DEFAULT GETDATE()
)
GO
CREATE TABLE QUANTIDADE(
	ID INT IDENTITY PRIMARY KEY,
	CULTURA INT NOT NULL,
	DATA_HORA DATETIME NOT NULL DEFAULT GETDATE()
)
GO
CREATE TABLE QUANTIDADE_ITEM(
	ID INT IDENTITY PRIMARY KEY,
	ITEM_INVESTIMENTO_ID INT NOT NULL,
	DATA_HORA DATETIME NOT NULL DEFAULT GETDATE()
)
GO
CREATE TABLE FORNECEDOR_INVESTIMENTO(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	TELEFONE CHAR(11) NOT NULL,
	EMAIL VARCHAR(150) NOT NULL
)
GO
CREATE TABLE FORNECEDOR_CUSTEIO(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	TELEFONE CHAR(11) NOT NULL,
	EMAIL VARCHAR(150) NOT NULL
)
GO
CREATE TABLE ITEM_INVESTIMENTO(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	MARCA VARCHAR(255) NOT NULL,
	ESPECIFICACAO VARCHAR(255) NOT NULL,
	QUANTIDADE INT NOT NULL,
	VALOR NUMERIC(10, 2) NOT NULL,
	FORNECEDOR_ID INT NOT NULL,
	DATA_HORA DATETIME NOT NULL DEFAULT GETDATE(),

	FOREIGN KEY(FORNECEDOR_ID) REFERENCES FORNECEDOR_INVESTIMENTO(ID)
)
GO
CREATE TABLE INVESTIMENTO(
	ID INT IDENTITY PRIMARY KEY,
	DATA_CADASTRO DATETIME NOT NULL DEFAULT GETDATE(),
	STATUS BIT NOT NULL DEFAULT 0,
	NOME_ASSOC VARCHAR(255) NOT NULL, 
	TOTAL_PROPOSTA NUMERIC(10,2),
	PROPOSTA_FINANCIADA NUMERIC(10,2),
	AUTORIZACAO_INVESTIMENTO VARCHAR(255) NOT NULL,
	DATA_APROVADA DATE NOT NULL,
	ORIGEM_PROPOSTA VARCHAR(255) NOT NULL,
	INFORMACAO_COMPLMT VARCHAR(255) NOT NULL,
	ITEM_ID INT NOT NULL,
	
	FOREIGN KEY (ID) REFERENCES ITEM_INVESTIMENTO(ID),
	FOREIGN KEY(ITEM_ID) REFERENCES QUANTIDADE_ITEM(ID)
)
GO
CREATE TABLE CUSTEIO(
	ID INT IDENTITY PRIMARY KEY,
	DATA_HORA DATETIME NOT NULL DEFAULT GETDATE(),
	STATUS BIT NOT NULL DEFAULT 0,
	ASSOCIADO_ID INT NOT NULL,
	VALOR_TOTAL NUMERIC(10, 2) NOT NULL,
	VALOR_FINANCIADO NUMERIC(10, 2) NOT NULL,
	AUTORIZACAO_CHEFE BIT NOT NULL DEFAULT 0,
	DATA_APROVACAO DATE NOT NULL,
	ORIGEM VARCHAR(255) NOT NULL,
	INFORMACAO_COMPLMT VARCHAR(255) NOT NULL,
	FINALIDADE_CUSTO VARCHAR(255),
	ITEM_ID INT NOT NULL,
	QUANTIDADE_ID INT NOT NULL,
	
	FOREIGN KEY (ITEM_ID) REFERENCES ITEM_INVESTIMENTO(ID),
	FOREIGN KEY (QUANTIDADE_ID) REFERENCES QUANTIDADE(ID)
)
GO
CREATE TABLE ITEM_CUSTEIO(
	ID INT IDENTITY PRIMARY KEY,
	DATA_HORA DATETIME NOT NULL DEFAULT GETDATE(),
	STATUS BIT NOT NULL DEFAULT 0,
	ASSOCIADO_ID INT NOT NULL,
	VALOR_TOTAL NUMERIC(10, 2) NOT NULL,
	VALOR_FINANCIADO NUMERIC(10, 2) NOT NULL,
	AUTORIZACAO_FORNECEDOR INT NOT NULL,
	DATA_APROVACAO DATE NOT NULL,
	ORIGEM VARCHAR(255) NOT NULL,
	INFORMACAO_COMPLMT VARCHAR(255) NOT NULL,
	FINALIDADE_CUSTO VARCHAR(255),
	ITEM_ID INT NOT NULL,
	QUANTIDADE_ID INT NOT NULL,
	
	FOREIGN KEY (AUTORIZACAO_FORNECEDOR) REFERENCES FORNECEDOR_CUSTEIO(ID),
	FOREIGN KEY (ITEM_ID) REFERENCES ITEM_INVESTIMENTO(ID),
	FOREIGN KEY (QUANTIDADE_ID) REFERENCES QUANTIDADE_ITEM(ID)	
)
GO
CREATE TABLE CLIENTE(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	IDADE INT NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	CELULAR CHAR(11) NOT NULL,
	DATA_HORA DATETIME NOT NULL DEFAULT GETDATE(),
	ASSOCIADO_ID INT,

	FOREIGN KEY (ASSOCIADO_ID) REFERENCES ASSOCIADO(ID)
)
