CREATE DATABASE BANCOINVESTIMENTO
GO
USE BANCOINVESTIMENTO
GO
CREATE TABLE CULTURA(
	ID INT IDENTITY PRIMARY KEY,
	LOCAL_ARMAZENAMENTO VARCHAR(100) NOT NULL,
	QUANTIDADE INT NOT NULL,
	DATA_HORA DATETIME DEFAULT GETDATE()
)
GO
CREATE TABLE ASSOCIADO(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	DATA_HORA DATETIME NOT NULL DEFAULT GETDATE()
)
GO
CREATE TABLE FORNECEDOR(
	ID INT IDENTITY PRIMARY KEY,
	NOME_FORNCEDOR VARCHAR(255) NOT NULL,
	TELEFONE CHAR(11) NOT NULL,
	EMAIL VARCHAR(150) NOT NULL
)
GO
CREATE TABLE INVESTIMENTO(
	ID INT IDENTITY PRIMARY KEY,
	DATA_CADASTRO DATETIME DEFAULT GETDATE(),
	STATUS BIT NOT NULL DEFAULT 0,
	ASSOC_ID INT NOT NULL, 
	TOTAL_PROPOSTA NUMERIC(10,2) NOT NULL,
	PROPOSTA_FINANCIADA NUMERIC(10,2) NOT NULL,
	AUTORIZACAO_INVESTIMENTO BIT NOT NULL DEFAULT 0,
	DATA_APROVADA DATE NOT NULL,
	ORIGEM_PROPOSTA VARCHAR(255) NOT NULL,
	INFORMACAO_COMPLMT VARCHAR(255),

	FOREIGN KEY (ASSOC_ID) REFERENCES ASSOCIADO(ID)
)
GO
CREATE TABLE ITEM_INVESTIMENTO(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	MARCA VARCHAR(255) NOT NULL,
	ESPECIFICACAO VARCHAR(255) NOT NULL,
	QUANTIDADE INT NOT NULL,
	VALOR NUMERIC(10, 2) NOT NULL,
	FORNECEDOR_ID INT NOT NULL,
	INVESTIMENTO_ID INT NOT NULL

	FOREIGN KEY(INVESTIMENTO_ID) REFERENCES INVESTIMENTO(ID),
	FOREIGN KEY(FORNECEDOR_ID) REFERENCES FORNECEDOR(ID)
)
GO
CREATE TABLE CUSTEIO(
	ID INT IDENTITY PRIMARY KEY,
	DATA_HORA DATETIME DEFAULT GETDATE(),
	STATUS BIT NOT NULL DEFAULT 0,
	ASSOC_ID INT NOT NULL,
	VALOR_TOTAL NUMERIC(10, 2) NOT NULL,
	VALOR_FINANCIADO NUMERIC(10, 2) NOT NULL,
	AUTORIZACAO_CHEFE BIT NOT NULL DEFAULT 0,
	DATA_APROVACAO DATE NOT NULL,
	ORIGEM VARCHAR(255) NOT NULL,
	INFORMACAO_COMPLMT VARCHAR(255),
	FINALIDADE_CUSTO VARCHAR(255) NOT NULL,
	
	FOREIGN KEY (ASSOC_ID) REFERENCES ASSOCIADO(ID),
)
GO
CREATE TABLE ITEM_CUSTEIO(
	ID INT IDENTITY PRIMARY KEY,
	DATA_HORA DATETIME DEFAULT GETDATE(),
	STATUS BIT NOT NULL DEFAULT 0,
	ASSOCIADO_ID INT NOT NULL,
	VALOR_TOTAL NUMERIC(10, 2) NOT NULL,
	VALOR_FINANCIADO NUMERIC(10, 2) NOT NULL,
	DATA_APROVACAO DATE NOT NULL,
	ORIGEM VARCHAR(255) NOT NULL,
	INFORMACAO_COMPLMT VARCHAR(255),
	FINALIDADE_CUSTO VARCHAR(255),
	CUSTEIO_ID INT NOT NULL,
	QUANTIDADE INT NOT NULL,
	FORNECEDOR_ID INT NOT NULL,
	
	FOREIGN KEY (CUSTEIO_ID) REFERENCES CUSTEIO(ID),
	FOREIGN KEY(FORNECEDOR_ID) REFERENCES FORNECEDOR(ID),
)
GO
CREATE TABLE CLIENTE(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	IDADE INT NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	CELULAR CHAR(11) NOT NULL,
	DATA_HORA DATETIME DEFAULT GETDATE(),
	ASSOCIADO_ID INT,

	FOREIGN KEY (ASSOCIADO_ID) REFERENCES ASSOCIADO(ID)
)
GO
INSERT INTO CULTURA (LOCAL_ARMAZENAMENTO, QUANTIDADE)
VALUES 
    ('GALINHEIRO', 10),
    ('CAMPO', 4),
    ('CELEIRO', 3)

INSERT INTO ASSOCIADO (NOME)
VALUES
    ('Luke Lindão'),
    ('Itachi Uchiha'),
    ('Kurisu Makise')

INSERT INTO FORNECEDOR (NOME_FORNCEDOR, TELEFONE, EMAIL)
VALUES
    ('John', '55987300012', 'john@gmail.com'),
    ('Ana', '55896320253', 'ana@gmail.com')

INSERT INTO INVESTIMENTO (STATUS, ASSOC_ID, TOTAL_PROPOSTA, PROPOSTA_FINANCIADA, AUTORIZACAO_INVESTIMENTO, DATA_APROVADA, ORIGEM_PROPOSTA, INFORMACAO_COMPLMT)
VALUES
    (0, 1, 5000.00, 4000.00, 0 , '2023-10-15', 'Santa Catarina', 'Aumentar a produção de produtos'),
    (1, 2, 8000.00, 6500.00, 1, '2023-10-20', 'São Paulo', 'Auxiliar equipamentos do campo')

INSERT INTO ITEM_INVESTIMENTO (NOME, MARCA, ESPECIFICACAO, QUANTIDADE, VALOR, FORNECEDOR_ID, INVESTIMENTO_ID)
VALUES
    ('Trator', 'New Holland', 'Plantação', 10, 100.00, 1, 1),
    ('Colheitadeira', 'Deutz', 'Cana de açucar', 5, 50.00, 2, 2)

INSERT INTO CUSTEIO (STATUS, ASSOC_ID, VALOR_TOTAL, VALOR_FINANCIADO, AUTORIZACAO_CHEFE, DATA_APROVACAO, ORIGEM, INFORMACAO_COMPLMT, FINALIDADE_CUSTO)
VALUES
    (0, 1, 6000.00, 4500.00, 1, '2023-11-05', 'São Paulo', NULL, 'Mercadoria'),
    (1, 2, 7500.00, 6000.00, 1, '2023-11-10', 'Santa Catarina', NULL, 'Mercadoria')

INSERT INTO ITEM_CUSTEIO (STATUS, ASSOCIADO_ID, VALOR_TOTAL, VALOR_FINANCIADO, DATA_APROVACAO, ORIGEM, INFORMACAO_COMPLMT, FINALIDADE_CUSTO, CUSTEIO_ID, QUANTIDADE, FORNECEDOR_ID)
VALUES
    (0, 1, 2000.00, 1500.00, '2023-11-06', 'São Paulo', 'Compra de alimentos', NULL, 1, 8, 1),
    (1, 2, 2800.00, 2200.00, '2023-11-12', 'Origem 6', 'Manutenção de equipamento', NULL, 2, 5, 2)

INSERT INTO CLIENTE (NOME, IDADE, EMAIL, CELULAR, ASSOCIADO_ID)
VALUES
    ('Maria', 21, 'maria@gmail.com', '55997514232', 1),
    ('Morgana', 28, 'morgana@gmail.com', '55987841533', 2)
